version: "3.3"

services:
  microservices-gateway:
    build: ./gateway
    expose:
      - 50050
    ports:
      - "50050:3000"
    environment:
      AUTH_URL: http://microservices-auth:50051/ # L'URL de l'authentification
      PRODUCTS_URL: http://microservices-products:50052/ # L'URL des produits
    networks:
      backend:

  microservices-auth:
    build: ./auth
    expose:
      - 50051
    ports:
      - "50051:50051"
    depends_on:
      mariadb-auth:
        condition: service_started
    networks:
      backend:

  microservices-products:
    build: ./products
    expose:
      - 50052
    ports:
      - "50052:50052"
    depends_on:
      mariadb-products:
        condition: service_started
    networks:
      backend:

  mariadb-auth:
    build: ./db-auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_AUTH}
      MYSQL_DATABASE: ${MYSQL_DATABASE_AUTH}
      MYSQL_USER: ${MYSQL_USER_AUTH}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_AUTH}
    expose:
      - 50055
    ports:
      - "50055:3306"
    volumes:
      - ./auth-data:/var/lib/mysql
      - ./db-auth:/docker-entrypoint-initdb.d
      - ./db-auth/encryption.cnf:/etc/mysql/conf.d/encryption.cnf
      - ./db-auth/compress.cnf:/etc/mysql/conf.d/compress.cnf
      - ./db-auth/keys.enc:/etc/mysql/conf.d/keys.enc
    networks:
      backend:

  mariadb-products:
    build: ./db-products
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_PRODUCTS}
      MYSQL_DATABASE: ${MYSQL_DATABASE_PRODUCTS}
      MYSQL_USER: ${MYSQL_USER_PRODUCTS}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PRODUCTS}
    expose:
      - 50056
    ports:
      - "50056:3307"
    volumes:
      - ./products-data:/var/lib/mysql
      - ./db-products:/docker-entrypoint-initdb.d
      - ./db-products/encryption.cnf:/etc/mysql/conf.d/encryption.cnf
      - ./db-products/compress.cnf:/etc/mysql/conf.d/compress.cnf
      - ./db-products/keys.enc:/etc/mysql/conf.d/keys.enc
    networks:
      backend:

networks:
  backend:
